openapi: 3.0.0
info:
  title: "A getting started API."
  version: "3.0.0"
paths: {}

components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    eventName:
      type: string
    Event:
      type: object
      properties:
        nonces:
          type: string
          description: >
            nonces
        eventName:
          type: string
          description: >
            eventName
        signingVersion:
          type: string
          description: >
            signingVersion
        maturationTime:
          type: string
          description: >
            maturationTime
        announcementSignature:
          type: string
          description: >
            announcementSignature
        eventDescriptorTLV:
          type: string
          description: >
            eventDescriptorTLV
        eventTLV:
          type: string
          description: >
            eventTLV
        announcementTLV:
          type: string
          description: >
            announcementTLV
        attestations:
          type: string
          description: >
            attestations
        signatures:
          type: string
          description: >
            signatures
        outcomes:
          type: string
          description: >
            outcomes
        signedOutcome:
          type: string
          description: >
            signedOutcome
    OraclePubkey:
      type: object
      properties:
        pubkey:
          type: string
          description: >
            Oracle's pubkey
    Events:
      type: array
      items:
        type: string
    Signatures:
      type: object
      properties:
        signatures:
          description: >
            signatures
          type: array
          items:
            type: string